name: Veracode Connect

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Veracode Connect
        uses: Afrika-Tecnologia/Veracode-Connect@v1
        with:
          veracode_api_id: ${{ secrets.VERACODE_API_ID }}
          veracode_api_key: ${{ secrets.VERACODE_API_KEY }}
          veracode_sca_token: ${{ secrets.VERACODE_SCA_TOKEN }}
          veracode_appname: ${{ github.repository_owner }}-${{ github.event.repository.name }}

          baseline_mode: 'repo'
          baseline_org: ${{ github.repository_owner }}
          baseline_github_app_id: ${{ secrets.BASELINE_GITHUB_APP_ID }}
          baseline_github_app_private_key: ${{ secrets.BASELINE_GITHUB_APP_PRIVATE_KEY }}
          baseline_github_app_installation_id: ${{ secrets.BASELINE_GITHUB_APP_INSTALLATION_ID }}

          enable_auto_packager: 'true'
          enable_pipelinescan: 'true'
          enable_sca: 'true'
          enable_iac: 'true'
          enable_upload_scan: 'true'

          policy_fail: 'false'
          fail_on_severity: 'Very High, High'
          fail_build: 'true'

          comment_pr: 'true'
          create_issues: 'true'
